# /Site settings
title: Case Zuiderveld
email: case@casetopher.me
description: The Jekyll version of the Spectral theme by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
topbar-display-name: Case Zuiderveld

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/zuidec
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/czuider/
linkedin_url: https://www.linkedin.com/in/case-zuiderveld/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
exclude: 
  - start-server
  - spectral_jekyll_theme.gemspec
  - database-credentials.php
  - api-key.php
  - build-copy
  - elements.md
